### ISSUE TITLE
otx GUI "Unable to process" file error

### ISSUE THREAD

**Issue by m-schmitt** [x43x61x69/otx#4]
Using otx build 565, when using the GUI, file loads and verifies. Click Save, a "Save As" dialog appears. Enter file name, click Save.

Result is:  Error processing file.
Unable to process *posix_file_path*.

Error occurs on all files.  Command line can process the same file.

Preferences are the defaults.

**Comment by x43x61x69** [comment]
Hi,

Guess the original developer never thought people would ever use those menu in the menu bar.

I'll take a look later but at the mean time, please use the auto generated file or set the path in the preferences.

PS. I've never used those since 2008, never knew till now!

Best,
Cai

**Comment by x43x61x69** [comment]
Hi @m-schmitt ,

It's fixed in Build 566.

Best,
Cai

**Comment by m-schmitt** [comment]
I was clicking the Save *button* not using the File > Save *menu*, but build 566 does fix it.

It's weird though... even the output name is in the Output box (regardless of the Filename preference), the Save dialog that appears when you click Save loses the file name. You have to reenter it.

**Comment by x43x61x69** [comment]
Hi @m-schmitt ,

Those two are not relevant. The save panel does not read anything from any UI fields. You can check out the source code to see how it works. (And indeed I could have made it that way, but not a priority to it's purpose.)

You are welcome to make changes and open a pull request if you wish this to be added. For now, I'd have to leave it as what it is till I have some spare time.

Best,
Cai
